# Generated by Django 3.0 on 2019-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
