# Generated by Django 3.0 on 2019-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0003_auto_20191215_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
