# Generated by Django 3.0 on 2019-12-31 21:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0005_auto_20191218_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='full_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
