# Generated by Django 3.0 on 2019-12-31 22:02

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0006_message_full_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='full_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder,
                                                                 null=True),
        ),
    ]
