# Generated by Django 3.0 on 2019-12-31 22:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0008_auto_20191231_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='full_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
