# Generated by Django 3.0 on 2020-01-01 17:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0009_auto_20191231_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
