# Generated by Django 3.0 on 2020-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0010_auto_20200101_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
