# Generated by Django 3.0 on 2020-01-01 17:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fbbot', '0011_auto_20200101_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='full_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
