# Generated by Django 3.0 on 2020-01-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbot', '0012_auto_20200101_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
