# Generated by Django 3.0 on 2019-12-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fbbot', '0003_auto_20191215_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CestLheureIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_listened', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbbot.Message')),
            ],
        ),
        migrations.CreateModel(
            name='CestLheure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_date', models.DateTimeField()),
                ('author', models.ForeignKey(default='message.author', on_delete=django.db.models.deletion.CASCADE,
                                             to='fbbot.User')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbbot.Message')),
            ],
            options={
                'ordering': ['-exact_date'],
                'get_latest_by': 'exact_date',
            },
        ),
    ]
