# Generated by Django 3.0 on 2020-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('front', '0004_remove_cestlheure_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cestlheure',
            name='type',
            field=models.CharField(default='sacred_hour', max_length=20),
        ),
    ]
